name: Build and Publish to GitHub Packages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Make Gradle executable
        run: chmod +x gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@017a9effdb900e5b5b2fddfb590a105619dca3c3

      - name: Publish to GitHub Packages
        run: ./gradlew publish
        env:
          githubActor: ${{ github.actor }}
          githubPassword: ${{ secrets.GITHUB_TOKEN }}
